### ISSUE TITLE
Error with parameter optimization using BayesSerachCV

### ISSUE THREAD

**Issue by tkmamidi** [M-e-r-c-u-r-y/Machine-Learning#2]
Hello,
I'm trying to build similar kinda NN and trying to optimize the parameters.
Below is my code - 

```
def create_model(neuronPct=0.1, neuronShrink =0.2, activation='relu', optimizer='Adam',  kernel_initializer='uniform', dropout=0.2):
    neuronCount = int(neuronPct * 1400)
    model = Sequential()
    layer = 0
    while neuronCount>5 and layer<10:
        if layer==0:
            model.add(Dense(neuronCount, 
                input_dim=n_columns, 
                activation=activation))
        else:
            model.add(Dense(neuronCount, activation=activation)) 
        layer += 1
        model.add(Dropout(dropout))
        neuronCount = neuronCount * neuronShrink

    model.add(Dense(units = 5, kernel_initializer=kernel_initializer,  activation = 'softmax')) # Note: no activation beyond this point    kernel_initializer=init, 
    model.compile(loss='categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])
    return model

params_dict ={'dropout': Real(0.01, 1.0),
              'neuronPct': Real(0.01, 1.0),
              'neuronShrink': Real(0.01, 1.0),
              'epochs': Integer(0,3),
              'batch_size': Integer(900,1000),
              'activation': Categorical(('relu', 'elu')), #'tanh', 'softmax', 'elu', 'softplus', 'softsign', 'relu', 'sigmoid', 'hard_sigmoid', 'linear', 'LeakyReLU', 'PReLU', 'ELU', 'ThresholdedReLU'
              'optimizer': Categorical(('Nadam', 'Adam')), #'SGD', 'RMSprop', 'Adagrad', 'Adadelta', 'Adam', 'Adamax', 'Nadam'
              'kernel_initializer': Categorical(('uniform','normal')) #,'uniform', 'lecun_uniform', 'normal', 'zero', 'glorot_normal', 'glorot_uniform', 'he_normal', 'he_uniform'
        }


search=True
if search:
    grid = BayesSearchCV(estimator=KerasClassifier(create_model, verbose=0), search_spaces=params_dict,cv=2, refit=True, # n_jobs=-1, iid=True, #scoring='accuracy',
                                  n_iter=5, verbose=2 ) #, scoring='accuracy'

    _ = grid.fit(X_train, y_train)
    print(f'Train score: {grid.best_score_}\nParameters: {grid.best_params_}\n')

```

However, I'm getting this error and I'm not sure why? Can you please help?
```
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/data/user/tmamidi/.conda/envs/envi/lib/python3.8/site-packages/skopt/searchcv.py", line 678, in fit
    optim_result = self._step(
  File "/data/user/tmamidi/.conda/envs/envi/lib/python3.8/site-packages/skopt/searchcv.py", line 566, in _step
    self._fit(X, y, groups, params_dict)
  File "/data/user/tmamidi/.conda/envs/envi/lib/python3.8/site-packages/skopt/searchcv.py", line 479, in _fit
    param_results["param_%s" % name][cand_i] = value
  File "/data/user/tmamidi/.conda/envs/envi/lib/python3.8/site-packages/sklearn/utils/deprecation.py", line 68, in wrapped
    return init(*args, **kwargs)
TypeError: object.__init__() takes exactly one argument (the instance to initialize)
```

Any help is much appreciated. Thanks in advance!

**Comment by M-e-r-c-u-r-y** [comment]
@tkmamidi It's been a couple years since I wrote this, haven't used it much since then but I'll give it a crack.

https://scikit-optimize.github.io/stable/modules/generated/skopt.BayesSearchCV.html
estimator : estimator object.
A object of that type is instantiated for each search point. This object is assumed to implement the scikit-learn estimator api. Either estimator needs to provide a score function, or scoring must be passed.

So the scoring parameter is a necessity as I don't think the KerasClassifier wrapper provides one.

Hope it helps :)

**Comment by tkmamidi** [comment]
Thanks for the comment. It was a bug in scikit-opt package. They recently fixed it and updating the package solved this. 
Thanks!
